import type { AssessmentQuestion, RoomId } from "./types";

export interface Room {
  id: RoomId;
  name: string;
  falseStory: string;
  parables: string;
  trueStory: string;
  calling: string;
  prompt: string;
  nextSteps: string[];
}

export const rooms: Room[] = [
  { id: "lost", name: "Lost", falseStory: "I do not belong.", parables: "Lost Sheep, Lost Coin, Lost Sons — Luke 15", trueStory: "You are sought, found, and welcomed home.", calling: "Heavenly Host", prompt: "Where has absence or shame become an identity, and how might being welcomed form me into a Heavenly Host?", nextSteps: ["Read Luke 15 slowly and notice who searches, waits, and welcomes.", "Offer a concrete welcome to someone who may feel unseen."] },
  { id: "scarcity", name: "Scarcity", falseStory: "There will never be enough.", parables: "Rich Fool — Luke 12; Laborers — Matthew 20", trueStory: "Life is received as gift, not secured by accumulation.", calling: "Planetary Trustee", prompt: "What am I storing, comparing, or controlling because I do not trust that life is gift?", nextSteps: ["Name three gifts you received today but did not secure for yourself.", "Release or share one thing you have been holding tightly."] },
  { id: "control", name: "Control", falseStory: "I must stay in control.", parables: "Unforgiving Servant — Matthew 18; Pharisee and Tax Collector — Luke 18", trueStory: "Grace frees us to forgive and release control.", calling: "Healer", prompt: "What debt, judgment, or comparison has become part of the architecture of my identity?", nextSteps: ["Name one outcome you cannot control and practice releasing it.", "Take one step toward mercy without demanding a particular response."] },
  { id: "stalled", name: "Stalled", falseStory: "I am not ready yet.", parables: "Talents — Matthew 25; Growing Seed — Mark 4", trueStory: "Faithfulness means participating before everything is clear.", calling: "Mentor & Coach", prompt: "What gift or next step have I buried while waiting to feel fully ready?", nextSteps: ["Give fifteen minutes to the gift or task you have postponed.", "Tell a trusted person the next small step you intend to take."] },
  { id: "boundary", name: "Boundary", falseStory: "Some people are outside God’s concern.", parables: "Good Samaritan — Luke 10; Great Banquet — Luke 14", trueStory: "Neighbor-love crosses the lines fear tries to protect.", calling: "Bridger", prompt: "Whom has my current story placed outside the reach of my responsibility, table, or compassion?", nextSteps: ["Listen to one person you usually encounter through assumptions.", "Make one practical gesture that widens your table or concern."] },
  { id: "settling", name: "Settling", falseStory: "This is all life can be.", parables: "Mustard Seed, Leaven, Hidden Treasure — Matthew 13", trueStory: "God’s kingdom awakens possibilities we stopped imagining.", calling: "Innovator & Imagineer", prompt: "What kingdom possibility have I stopped imagining because I am protecting an arrangement that feels safe?", nextSteps: ["Write down one kingdom possibility you have stopped naming.", "Try one low-risk experiment that makes room for new life."] },
  { id: "delay", name: "Delay", falseStory: "I will respond later.", parables: "Wise Virgins — Matthew 25; Two Sons — Matthew 21", trueStory: "God’s kingdom calls for faithful response today.", calling: "WayMaker", prompt: "What faithful response am I postponing, and what path could today’s yes open for others?", nextSteps: ["Complete one faithful action today in under twenty minutes.", "Remove one obstacle that keeps a needed path closed for others."] },
  { id: "distraction", name: "Distraction", falseStory: "My attention belongs everywhere else.", parables: "Sower — Luke 8; Hidden Treasure — Matthew 13", trueStory: "Attention is discipleship; what we notice shapes who we become.", calling: "Awakener", prompt: "What repeatedly captures my attention, and how might disciplined noticing form me into an Awakener?", nextSteps: ["Choose ten minutes of undivided attention without a device.", "Write what takes your attention and what you want to notice instead."] }
];

export const roomById = Object.fromEntries(rooms.map((room) => [room.id, room])) as Record<RoomId, Room>;

const q = (id: string, room: RoomId, dimension: AssessmentQuestion["dimension"], text: string): AssessmentQuestion => ({ id, room, dimension, text });
export const questions: AssessmentQuestion[] = [
  q("lost_01","lost","story","I sometimes wonder whether I truly belong, even when I have been included."), q("boundary_01","boundary","story","I feel more secure when I clearly know who is with me and who is not."), q("control_01","control","story","I often feel responsible for making sure important things turn out correctly."), q("stalled_01","stalled","story","There are parts of my life where I know something needs to change, but I keep circling around the same issues."), q("settling_01","settling","story","In some areas of life, I have lowered my expectations because expecting more feels unrealistic."), q("scarcity_01","scarcity","story","Even when things are going reasonably well, I can worry about losing what I have or not having enough."), q("delay_01","delay","story","There are important conversations, decisions, or changes I know I should address but continue postponing."), q("distraction_01","distraction","story","When something uncomfortable is happening inside me, my attention quickly moves toward something else."),
  q("control_02","control","emotion","Uncertainty makes me want to take charge when something important is at stake."), q("scarcity_02","scarcity","emotion","I notice how my opportunities, resources, success, or recognition compare with what other people receive."), q("lost_02","lost","emotion","Being overlooked, excluded, or forgotten affects me more than I would like."), q("delay_02","delay","emotion","I often find myself waiting for a better time before dealing with something difficult."), q("boundary_02","boundary","emotion","People whose beliefs, behavior, lifestyle, or values are very different from mine can quickly make me defensive."), q("distraction_02","distraction","emotion","Quiet or unstructured time can make me restless because my mind immediately looks for something to engage."), q("settling_02","settling","emotion","Past disappointment makes it difficult for me to believe meaningful change will actually last."), q("stalled_02","stalled","emotion","I frequently intend to make a change but struggle to create sustained movement."),
  q("distraction_03","distraction","strategy","I can keep myself constantly busy, entertained, connected, informed, or occupied."), q("stalled_03","stalled","strategy","Thinking, talking, researching, or planning about change can sometimes take the place of actually beginning."), q("boundary_03","boundary","strategy","I tend to keep emotional or relational distance from people I strongly disagree with."), q("lost_03","lost","strategy","I adjust how I present myself depending on whose acceptance or approval I want."), q("scarcity_03","scarcity","strategy","Under pressure, I tend to protect my own time, money, comfort, opportunities, or interests first."), q("settling_03","settling","strategy","I sometimes avoid taking a risk because I doubt the result will be worth the effort."), q("control_03","control","strategy","I have difficulty letting someone handle something their way when I believe my way would work better."), q("delay_03","delay","strategy","When a decision or conversation will be uncomfortable, postponing it gives me temporary relief."),
  q("settling_04","settling","shadow","When people become enthusiastic about changing something, part of me quickly notices why it probably will not work."), q("lost_04","lost","shadow","When I feel insecure or unnoticed, I may work harder to get reassurance, attention, or recognition."), q("delay_04","delay","shadow","I sometimes wait for another person or circumstance to change before taking responsibility for what I can do."), q("control_04","control","shadow","When people ignore my expectations or advice, I can become impatient, critical, forceful, angry, or withdrawn."), q("distraction_04","distraction","shadow","I sometimes become absorbed in conflict, outrage, gossip, or drama that does not actually address what is happening in my own life."), q("boundary_04","boundary","shadow","When someone frustrates me, I can become sarcastic, dismissive, or talk about what is wrong with them to other people."), q("stalled_04","stalled","shadow","When something in my life is not working, I can focus first on the people or circumstances making change difficult."), q("scarcity_04","scarcity","shadow","When someone receives an opportunity or recognition I wanted, part of me can feel that I deserved it more."),
  q("scarcity_05","scarcity","mirror","Someone else's gain can sometimes feel like a loss for me."), q("boundary_05","boundary","mirror","Once I have decided what kind of person someone is, I find it difficult to see them differently."), q("stalled_05","stalled","mirror","I can sometimes explain why I am stuck more easily than I can explain what I am currently doing about it."), q("distraction_05","distraction","mirror","Other people's problems can be easier for me to focus on than my own."), q("control_05","control","mirror","People close to me might say I sometimes try to manage them rather than simply relate to them."), q("lost_05","lost","mirror","People close to me might say I need more affirmation or reassurance than I realize."), q("delay_05","delay","mirror","I can avoid an apology, decision, or difficult conversation and hope the situation eventually settles down on its own."), q("settling_05","settling","mirror","People close to me might say I dismiss new possibilities too quickly.")
];
export const questionPages = Array.from({ length: 5 }, (_, page) => questions.slice(page * 8, page * 8 + 8));
export const scaleLabels = ["Almost Never", "Rarely", "Sometimes", "Often", "Very Often"];
export const ASSESSMENT_VERSION = "2.0-story-strategy-shadow";
export const CLOSE_SECONDARY_THRESHOLD = 0.25;

export const roomInsights: Record<RoomId, { story: string; strength: string; protects: string; shadowLabel: string; shadow: string; relationalCost: string; question: string }> = {
  lost:{story:"I need to be chosen, noticed, or accepted in order to know that I belong.",strength:"You may be socially perceptive, adaptable, relationally aware, and sensitive to whether people feel included.",protects:"Rejection, invisibility, abandonment, or the fear that your authentic self will not be enough.",shadowLabel:"Approval-Seeking",shadow:"The desire to belong can become performing, people-pleasing, needing reassurance, seeking attention, or changing yourself to remain accepted.",relationalCost:"Other people may feel pressure to continually reassure you or may struggle to know when they are encountering the real you rather than the version of you seeking acceptance.",question:"Who would you be if belonging were received rather than earned?"},
  boundary:{story:"I am safer when I know who belongs with me and who does not.",strength:"You may have strong convictions, loyalty, discernment, and a deep desire to protect people and values that matter.",protects:"Threat, betrayal, contamination, loss of identity, or uncertainty about whom you can trust.",shadowLabel:"Us vs. Them",shadow:"Conviction and belonging can harden into contempt, cliques, gossip, scapegoating, suspicion, or reducing people to categories.",relationalCost:"People outside your trusted circle may feel categorized before they feel known, while those inside the circle may learn that belonging requires staying on the correct side.",question:"Who becomes difficult for you to see as a whole person?"},
  control:{story:"If I don't keep things together, something important may fall apart.",strength:"You may be responsible, competent, decisive, dependable, and willing to carry weight others avoid.",protects:"Chaos, failure, vulnerability, disappointment, or being dependent on someone unreliable.",shadowLabel:"Power-Grabbing",shadow:"Responsibility can become criticism, micromanagement, anger, manipulation, scorekeeping, pressure, or difficulty admitting you were wrong.",relationalCost:"Other people may experience your responsibility as pressure and may feel there is little room to contribute, fail, disagree, or do things differently.",question:"What are you trying to prevent by keeping such a tight grip on the outcome?"},
  stalled:{story:"I want things to change, but something keeps me from actually moving.",strength:"You may be reflective, thoughtful, careful, imaginative, and able to see complexities before acting.",protects:"Failure, regret, embarrassment, responsibility, or discovering that effort may not work.",shadowLabel:"Blaming",shadow:"Reflection can become excuses, chronic criticism, talking without acting, or explaining your lack of movement primarily through other people's failures.",relationalCost:"People around you may grow frustrated when insight, intention, or criticism repeatedly fails to become action.",question:"What have you been explaining that may actually require a first step?"},
  settling:{story:"Expecting less protects me from being disappointed again.",strength:"You may be realistic, resilient, cautious about empty promises, and less easily swept up by hype.",protects:"Disappointment, grief, wasted effort, or the pain of hoping again.",shadowLabel:"Cynicism",shadow:"Realism can harden into resignation, sarcasm, defensiveness, refusal to risk, or ‘That's just how things are.’",relationalCost:"Your realism may unintentionally drain hope from relationships or discourage people who are trying to imagine something new.",question:"Where has disappointment quietly convinced you to stop imagining?"},
  scarcity:{story:"There may not be enough, so I need to protect what is mine.",strength:"You may be resourceful, disciplined, prepared, hardworking, and attentive to stewardship.",protects:"Loss, insecurity, dependence, falling behind, or discovering there is not enough.",shadowLabel:"Entitlement",shadow:"Stewardship can become comparison, envy, hoarding, competition, possessiveness, or believing you deserve more than someone else.",relationalCost:"Others may experience competition where you intend prudence, or feel that your security consistently receives priority over shared flourishing.",question:"What are you protecting because you fear there may not be enough?"},
  delay:{story:"I can deal with this later, when the timing or circumstances are better.",strength:"You may be patient, deliberative, resistant to impulsive decisions, and capable of waiting when waiting is wise.",protects:"Conflict, discomfort, irreversible decisions, accountability, or immediate consequences.",shadowLabel:"Avoidance",shadow:"Patience can become procrastination, avoiding responsibility, postponing apologies, resisting difficult conversations, or waiting for someone else to move first.",relationalCost:"Other people may carry unresolved tension while waiting for conversations, decisions, apologies, or actions that you continue postponing.",question:"What are you waiting to become easier before you finally address it?"},
  distraction:{story:"Anything may feel easier to face than what is happening inside me right now.",strength:"You may be curious, energetic, responsive, highly aware of your environment, and able to engage many things at once.",protects:"Pain, silence, unresolved questions, uncomfortable emotions, or sustained self-examination.",shadowLabel:"Drama",shadow:"Curiosity and activity can become constant busyness, outrage, gossip, relational drama, entertainment, or focusing on everyone else's problems rather than your own.",relationalCost:"People may experience you as present to everything happening around you while strangely unavailable to what is happening within you or between you and them.",question:"What becomes harder to hear when your life stays noisy?"}
};
